Introduction
============

About
-----

The ``nislsc`` package enables Python applications to configure and control
NI-SLSC chassis and modules.

NI created and supports this package.

Operating System Support
------------------------

``nislsc`` supports Windows and Linux operating systems.

Python Version Support
----------------------

``nislsc`` supports CPython 3.9+ and PyPy3.

Installation
------------

You can install the ``nislsc`` package using ``pip`` or by listing it as a
dependency in your project's ``pyproject.toml`` file.
