name: Build

on:
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: ni/python-actions/setup-python@aa64e60612cb078b0c2ada666becbd70d4817d55 # v0.7.1
        id: setup-python
      - name: Set up Poetry
        uses: ni/python-actions/setup-poetry@aa64e60612cb078b0c2ada666becbd70d4817d55 # v0.7.1
      - name: Cache virtualenv (all extras)
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: .venv
          key: nislsc-${{ runner.os }}-py${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install
      - name: Run linters
        run: poetry run ni-python-styleguide lint
      - name: Run mypy (Linux)
        run: poetry run mypy
      - name: Run mypy (Windows)
        run: poetry run mypy --platform win32
      - name: Run Bandit security checks
        run: poetry run bandit -c pyproject.toml -r generated/nislsc
      - name: Generate ni-slsc files
        run: |
          rm -fr generated/nislsc
          poetry run python src/codegen/generator.py
      - name: Check for files dirtied by codegen
        run: git diff --exit-code
