name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  check_docs:
    name: Check docs
    uses: ./.github/workflows/check_docs.yml
  check_workflows:
    name: Check workflows
    uses: ./.github/workflows/check_workflows.yml
    permissions:
      actions: read
      contents: read
      security-events: write
  checks_succeeded:
    name: Checks succeeded
    needs: [build, check_docs, check_workflows]
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: exit 0
  run_unit_tests:
    name: Run unit tests
    uses: ./.github/workflows/run_unit_tests.yml
    needs: [checks_succeeded]
  # run_system_tests:
  #   name: Run system tests
  #   uses: ./.github/workflows/run_system_tests.yml
  #   needs: [build, run_unit_tests]
  report_test_results:
    name: Report test results
    uses: ./.github/workflows/report_test_results.yml
    needs: [run_unit_tests]
    if: always()
    permissions:
      contents: read
      checks: write
      pull-requests: write
